all: hello

hello: main.cpp factorial.cpp hello.cpp
	g++ main.o factorial.o hello.o -o hello

main.cpp:
	g++ -c main.cpp

factorial.cpp:
	g++ -c factorial.cpp

hello.cpp: saycmd
	g++ -c hello.cpp

clean:
	rm -rf *.o hello

saycmd:
    echo "I love this"
